In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [3]:
df = pd.read_csv('cardekho_imputated.csv', index_col = [0])

df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19537,Hyundai i10,Hyundai,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5,250000
19540,Maruti Ertiga,Maruti,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7,925000
19541,Skoda Rapid,Skoda,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5,425000
19542,Mahindra XUV500,Mahindra,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7,1225000
19543,Honda City,Honda,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5,1200000

In [4]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [5]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [6]:
df.drop('car_name', axis = 1, inplace = True)

df.drop('brand', axis = 1, inplace = True)

In [7]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [8]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [9]:
#numerical features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))

#categorical features
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features :', len(cat_features))

#discrete features
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))

#continuous features
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features :',len(continuous_features))

Num of Numerical Features : 7
Num of Categorical Features : 4
Num of Discrete Features : 2
Num of Continuous Features : 5

In [10]:
from sklearn.model_selection import train_test_split

X = df.drop(['selling_price'], axis = 1)
y = df['selling_price']

In [11]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [12]:
#onehotencoding
len(df['model'].unique())

120

In [13]:
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [14]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [15]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [16]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [17]:
num_features = X.select_dtypes(exclude="object").columns
onehot_columns = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, onehot_columns),
        ("StandardScaler", numeric_transformer, num_features)
        
    ],remainder='passthrough'
    
)

In [18]:
X = preprocessor.fit_transform(X)

In [19]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

X_train.shape, X_test.shape

((12328, 14), (3083, 14))

In [21]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]])

In [22]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [23]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [24]:
#training the model
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),
   
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    #predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    #train and test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 553855.6665
- Mean Absolute Error: 268101.6071
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502543.5930
- Mean Absolute Error: 279618.5794
- R2 Score: 0.6645
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 553855.6710
- Mean Absolute Error: 268099.2226
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502542.6696
- Mean Absolute Error: 279614.7461
- R2 Score: 0.6645
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 553856.3160
- Mean Absolute Error: 268059.8015
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502533.8230
- Mean Absolute Error: 279557.2169
- R2 Score: 0.6645
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 325881.5005
- Mean Absolute Error: 91396.5445
- R2 Score: 0.8691
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 253138.6083
- Mean Absolute Error: 112578.2436
- R2 Score: 0.9149
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 20797.2352
- Mean Absolute Error: 5164.8199
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 298504.6552
- Mean Absolute Error: 124126.0866
- R2 Score: 0.8816
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 137804.6769
- Mean Absolute Error: 40164.6410
- R2 Score: 0.9766
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 231201.9482
- Mean Absolute Error: 102185.3588
- R2 Score: 0.9290
===================================

In [25]:
knn_params = {"n_neighbors": [2, 3, 10, 20, 40, 50]} #for hyperparameter tuning
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

In [27]:
#models list for Hyperparameter tuning
randomcv_models = [('KNN', KNeighborsRegressor(), knn_params),
                   ("RF", RandomForestRegressor(), rf_params)
                   
                   ]

In [32]:
#hyperparameter Tuning
import multiprocessing as mp
mp.set_start_method("fork", force=True)

from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=2,
                                   n_jobs=-1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.7s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=500; total time=   4.4s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=1000; total time=   7.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.7s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=   3.6s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=   5.3s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=   6.8s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.9s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=1000; total time=   6.0s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=200; total time=   0.7s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=200; total time=   0.8s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   8.9s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   3.8s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=500; total time=   4.5s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=1000; total time=   7.2s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=   5.1s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=   5.3s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.2s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.0s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=  11.1s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   4.0s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=500; total time=   4.5s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=   7.7s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=200; total time=   1.4s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=1000; total time=   4.3s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=1000; total time=   4.2s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=1000; total time=   6.4s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   9.4s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.8s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=1000; total time=   5.3s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=500; total time=   5.2s
[CV] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=1000; total time=   6.8s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.6s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   1.5s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=500; total time=   4.6s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=500; total time=   4.1s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=100; total time=   0.8s
[CV] END max_depth=None, max_features=7, min_samples_split=15, n_estimators=1000; total time=   9.2s
[CV] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=100; total time=   0.4s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=1000; total time=   3.8s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=   3.7s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=1000; total time=   7.1s
[CV] END max_depth=15, max_features=8, min_samples_split=8, n_estimators=200; total time=   2.0s
Fitting 3 folds for each of 6 candidates, totalling 18 fits

Exception ignored in: <function ResourceTracker.__del__ at 0x107149800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x105f81800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x103169800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x107769800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x104141800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x105ac9800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x121071800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END ......................................n_neighbors=2; total time=   0.0s
[CV] END .....................................n_neighbors=40; total time=   0.2s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=500; total time=   2.1s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.3s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.3s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=500; total time=   3.4s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=500; total time=   3.3s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=   7.1s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=   7.3s

Exception ignored in: <function ResourceTracker.__del__ at 0x1076d9800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END ......................................n_neighbors=3; total time=   0.1s
[CV] END .....................................n_neighbors=50; total time=   0.2s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=500; total time=   2.1s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=   6.3s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=200; total time=   1.1s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=200; total time=   1.9s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=200; total time=   2.0s
[CV] END max_depth=5, max_features=7, min_samples_split=8, n_estimators=500; total time=   2.1s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=   9.0s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000; total time=  10.1s

Exception ignored in: <function ResourceTracker.__del__ at 0x1063fd800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END .....................................n_neighbors=10; total time=   0.1s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=500; total time=   4.8s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.7s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.5s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.4s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=1000; total time=   7.6s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=200; total time=   1.6s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=1000; total time=   4.6s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000; total time=  10.0s

Exception ignored in: <function ResourceTracker.__del__ at 0x1079d9800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END ......................................n_neighbors=2; total time=   0.0s
[CV] END .....................................n_neighbors=40; total time=   0.2s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.6s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=500; total time=   4.7s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.7s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=500; total time=   2.7s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.5s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=1000; total time=   7.7s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=500; total time=   3.2s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.0s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.2s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000; total time=  10.2s

Exception ignored in: <function ResourceTracker.__del__ at 0x107089800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END .....................................n_neighbors=10; total time=   0.1s
[CV] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=500; total time=   2.2s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=500; total time=   3.3s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=500; total time=   3.4s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=1000; total time=   6.6s
[CV] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=1000; total time=   7.3s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.0s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.2s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=  11.5s

Exception ignored in: <function ResourceTracker.__del__ at 0x104e5d800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END .....................................n_neighbors=10; total time=   0.1s
[CV] END max_depth=15, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.8s
[CV] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=200; total time=   1.3s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=   6.3s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=1000; total time=   6.2s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=   8.9s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.2s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.8s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=  11.5s

Exception ignored in: <function ResourceTracker.__del__ at 0x1047cd800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END ......................................n_neighbors=3; total time=   0.0s
[CV] END .....................................n_neighbors=50; total time=   0.2s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   0.7s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=500; total time=   4.8s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500; total time=   2.0s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=200; total time=   0.7s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=200; total time=   1.5s
[CV] END max_depth=15, max_features=auto, min_samples_split=8, n_estimators=1000; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=5, max_features=8, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=8, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.4s
[CV] END max_depth=10, max_features=8, min_samples_split=2, n_estimators=1000; total time=   7.7s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=8, min_samples_split=8, n_estimators=500; total time=   3.3s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.5s
[CV] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=100; total time=   0.6s
[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.9s
[CV] END max_depth=10, max_features=8, min_samples_split=8, n_estimators=100; total time=   0.8s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=1000; total time=  11.6s

Exception ignored in: <function ResourceTracker.__del__ at 0x1032d1800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=100; total time=   0.5s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=500; total time=   6.6s

Exception ignored in: <function ResourceTracker.__del__ at 0x1073c9800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END max_depth=15, max_features=8, min_samples_split=20, n_estimators=100; total time=   0.9s
[CV] END max_depth=None, max_features=5, min_samples_split=15, n_estimators=100; total time=   0.7s
[CV] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=500; total time=   3.5s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=1000; total time=   6.7s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=500; total time=   6.6s

Exception ignored in: <function ResourceTracker.__del__ at 0x104d75800>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 84, in __del__
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 93, in _stop
  File "/opt/anaconda3/lib/python3.13/multiprocessing/resource_tracker.py", line 118, in _stop_locked
ChildProcessError: [Errno 10] No child processes

---------------- Best Params for KNN -------------------
{'n_neighbors': 10}
---------------- Best Params for RF -------------------
{'n_estimators': 100, 'min_samples_split': 2, 'max_features': 7, 'max_depth': 15}

In [34]:
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=100, min_samples_split=2, max_features='sqrt', max_depth=None, 
                                                     n_jobs=-1),
     "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=10, n_jobs=-1)
     
} #retrainig the models
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)
    
    print(list(models.keys())[i])
    
    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')
    
    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))
    
    print('='*35)
    print('\n')

Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 143057.8100
- Mean Absolute Error: 39977.9012
- R2 Score: 0.9748
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 205946.6755
- Mean Absolute Error: 98983.9793
- R2 Score: 0.9437
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 363444.3871
- Mean Absolute Error: 103455.4916
- R2 Score: 0.8371
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 263863.6616
- Mean Absolute Error: 117441.9802
- R2 Score: 0.9075
===================================